[package]
name = "server"
version = "0.1.0"
authors = ["Oleg Gashev <oleg@gashev.net>"]
edition = "2018"

[dependencies]
futures = "0.1"
grpcio = "0.4"
protobuf = { version = "2.8.1", features = ["with-bytes"] }
db = { path = "../db" }
diesel = { version = "1.0.0", features = ["postgres"] }