version: '3.1'

services:
  db:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: books
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  grpc-server:
    image: docker-local:5000/grpc-server
    restart: always
    ports:
      - "50051:50051"